/*
 * KML export for Google Earth review. Classic script: window.TechumKML.
 */
(function (root) {
  'use strict';

  function esc(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }
  function coordString(latLonPath) {
    return latLonPath.map((p) => `${p.lon},${p.lat},0`).join(' ');
  }
  function polygonPlacemark(name, latLonPath, styleId) {
    const closed = latLonPath.concat([latLonPath[0]]);
    return `  <Placemark>
    <name>${esc(name)}</name>
    <styleUrl>#${styleId}</styleUrl>
    <Polygon><outerBoundaryIs><LinearRing><coordinates>${coordString(closed)}</coordinates></LinearRing></outerBoundaryIs></Polygon>
  </Placemark>`;
  }
  function style(id, lineColorAabbggrr, width, fillColorAabbggrr) {
    return `  <Style id="${id}">
    <LineStyle><color>${lineColorAabbggrr}</color><width>${width}</width></LineStyle>
    <PolyStyle><color>${fillColorAabbggrr}</color></PolyStyle>
  </Style>`;
  }

  // layers: {pin:{lat,lon}, techum, city, karpef, second: latLonPaths or null}
  // configText: human-readable settings dump for the description.
  function buildKML(layers, configText) {
    const parts = [];
    parts.push('<?xml version="1.0" encoding="UTF-8"?>');
    parts.push('<kml xmlns="http://www.opengis.net/kml/2.2"><Document>');
    parts.push(`<name>Techum Shabbos (DRAFT — requires review by a rav/mumcheh)</name>`);
    parts.push(`<description>${esc('DRAFT ONLY — NOT a psak halacha. Generated by Techum Calculator.\n\nActive configuration:\n' + configText)}</description>`);
    parts.push(style('techum', 'ff0000ff', 3, '1a0000ff'));
    parts.push(style('city', 'ffff8800', 2, '1aff8800'));
    parts.push(style('karpef', 'ffaaaa00', 2, '00ffffff'));
    parts.push(style('second', 'ffff00aa', 2, '00ffffff'));
    if (layers.pin) {
      parts.push(`  <Placemark><name>Shevisa point</name><Point><coordinates>${layers.pin.lon},${layers.pin.lat},0</coordinates></Point></Placemark>`);
    }
    if (layers.city) parts.push(polygonPlacemark('City rectangle (ribua ha’ir)', layers.city, 'city'));
    if (layers.karpef) parts.push(polygonPlacemark('Karpef (+70⅔ amos)', layers.karpef, 'karpef'));
    if (layers.techum) parts.push(polygonPlacemark('TECHUM boundary (2000 amos)', layers.techum, 'techum'));
    if (layers.second) parts.push(polygonPlacemark('Comparison shita techum', layers.second, 'second'));
    parts.push('</Document></kml>');
    return parts.join('\n');
  }

  function download(filename, text, mime) {
    const blob = new Blob([text], { type: mime || 'application/vnd.google-earth.kml+xml' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = filename;
    a.click();
    URL.revokeObjectURL(a.href);
  }

  root.TechumKML = { buildKML, download };
})(typeof self !== 'undefined' ? self : this);
