ALTER TABLE daily_totals ADD COLUMN search_found INTEGER NOT NULL DEFAULT 0;
ALTER TABLE daily_totals ADD COLUMN city_calcs INTEGER NOT NULL DEFAULT 0;
ALTER TABLE daily_totals ADD COLUMN point_calcs INTEGER NOT NULL DEFAULT 0;
ALTER TABLE daily_totals ADD COLUMN cache_hits INTEGER NOT NULL DEFAULT 0;
